kind: wasmer.io/App.v0
name: notesapi
owner: megzinx
package: .

annotations:
  anybuild.run/config:
    commands:
      start: uvicorn config.wsgi:application --interface=wsgi --host 0.0.0.0 --port $PORT
    python_framework: django
    python_server: uvicorn
    wsgi_application: config.wsgi:application
    python_install_inputs:
    - requirements.txt
    python_migration_strategy: django